service: chatbot-python-function

provider:
  name: scaleway
  runtime: python310
  scwToken: ${env:SCW_SECRET_ACCESS_KEY}  
  scwProject: ${env:SCW_PROJECT_ID}
  secret:
    SECRET_KEY: ${env:SECRET_KEY}


plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!bin/**'
    - '!.gitignore'
    - '!.idea'
    - '!.git/**'

functions:
  chatbot-python:
    handler: app/chatbot.handle
    env:
      database_model: english-corpus.sqlite3
